/* prettier-ignore-start */

/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.27.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { api as events } from "../events";
import { api as matches } from "../matches";
import { api as players } from "../players";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = {
    events,
    matches,
    players,
};

/* prettier-ignore-end */
