/**
 * Generated by convex@1.27.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { GenericQueryCtx, GenericMutationCtx, GenericActionCtx, DataModel } from "convex/server";
import { FunctionReference } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * import { api } from "./_generated/api";
 * ```
 */
export declare const mutation: <ArgsValidator extends Record<string, any>, Output>(
  func: (ctx: GenericMutationCtx<DataModel>, args: ArgsValidator) => Promise<Output>
) => FunctionReference<"mutation", "public", ArgsValidator, Output>;

export declare const query: <ArgsValidator extends Record<string, any>, Output>(
  func: (ctx: GenericQueryCtx<DataModel>, args: ArgsValidator) => Promise<Output>
) => FunctionReference<"query", "public", ArgsValidator, Output>;

export declare const action: <ArgsValidator extends Record<string, any>, Output>(
  func: (ctx: GenericActionCtx<DataModel>, args: ArgsValidator) => Promise<Output>
) => FunctionReference<"action", "public", ArgsValidator, Output>;
