/**
 * Generated by convex@1.27.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

export const mutation = (func) => func;
export const query = (func) => func;
export const action = (func) => func;
